stages:
  - build
  - test
  - deploy

image: registry.pro-sales.ch/docker/php-ci-runner:1.1.0

install_composer_dependencies:
  stage: build
  cache:
    key: composer
    paths:
      - vendor/
  script:
    - composer install --no-progress --no-suggest --ignore-platform-reqs

run_tests:
  stage: test
  cache:
    key: composer
    paths:
      - vendor/
    policy: pull
  script:
    - echo -e "section_end:"`date +%s`":build_script\r\e[0Ksection_start:"`date +%s`":phpunit_cache_xdebug_filter\r\e[0KCaching xdebug filters"
    - php vendor/bin/phpunit --dump-xdebug-filter .xdebug-filter-dump.php
    - echo -e "section_end:"`date +%s`":phpunit_cache_xdebug_filter\r\e[0Ksection_start:"`date +%s`":phpunit_run_testsuite\r\e[0KRunning test suite"
    - php vendor/bin/phpunit --prepend .xdebug-filter-dump.php --coverage-text --colors=never
    - echo -e "section_end:"`date +%s`":phpunit_run_testsuite\r\e[0Ksection_start:"`date +%s`":build_script\r\e[0K"

code_quality:
  stage: test
  allow_failure: true
  cache:
    key: composer
    paths:
      - vendor/
    policy: pull
  script:
    - php vendor/bin/phpcs -p -n --report=summary --standard=PSR2 app

deploy_to_forge_dev_server:
  stage: deploy
  only:
    - master
  environment: dev
  except:
    variables:
      - $FORGE_DEV_DEPLOYMENT_URL == null
  script:
    - curl $FORGE_DEV_DEPLOYMENT_URL

deploy_to_forge_live_server:
  stage: deploy
  only:
    - master
  when: manual
  environment: live
  except:
    variables:
      - $FORGE_LIVE_DEPLOYMENT_URL == null
  script:
    - curl $FORGE_LIVE_DEPLOYMENT_URL
