version: '2'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: [PROJECT]/app
    ports:
     - "${APP_PORT}:80"
    environment:
      CONTAINER_ENV: "${APP_ENV}"
      XDEBUG_HOST: "${XDEBUG_HOST}"
      WWWUSER: "${WWWUSER}"
    volumes:
     - .:/var/www/html:delegated
    networks:
     - [PROJECT]
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
      args:
        uid: "${WWWUSER}"
    image: [PROJECT]/node
    user: node
    command:
      - node_modules/.bin/laravel-echo-server
      - start
    volumes:
     - .:/var/www/html:delegated
    networks:
     - [PROJECT]
  mysql:
    image: mysql:5.7
    ports:
     - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
     - mysqldata:/var/lib/mysql
     # - ./docker/mysql/conf.d:/etc/mysql/conf.d
     # - ./docker/mysql/logs:/var/log/mysql
    networks:
     - [PROJECT]
  redis:
    image: redis:alpine
    volumes:
     - redisdata:/data
    networks:
     - [PROJECT]

networks:
  [PROJECT]:
    driver: "bridge"

volumes:
  mysqldata:
    driver: "local"
  redisdata:
    driver: "local"
